# Publish Docker image
name: Publish Docker image on Docker Hub

on:
  push:
    branches: 
      - 'main'
      - 'master'

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker base
        uses: docker/build-push-action@v2 # https://github.com/docker/build-push-action
        with:
          context: docker/docker_base
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}/docker_base:latest        
